CREATE TABLE `plano_associado` (
 `COD_ASSOCIADO` int(11) NOT NULL,
 `COD_PLANO` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `detalhes_plano` (
 `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
 `COD_PLANO` int(11) NOT NULL,
 `NUM_AGENDAMENTOS` int(11) DEFAULT '50',
 `NUM_SERVICOS` int(11) DEFAULT '2',
 `LEMBRETE_EMAIL` tinyint(1) DEFAULT '0',
 `NUM_TEMPLATES` int(11) DEFAULT NULL,
 `PERSONALIZA_TEMPLATE` tinyint(1) DEFAULT '0',
 `NUM_FOTOS_LOCAL` int(11) DEFAULT '2',
 `PRAZO_AGENDAMENTO` int(11) DEFAULT '2',
 `NUM_FUNCIONARIO_LOCAL` int(11) DEFAULT '2',
 PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE  `detalhes_plano` ADD INDEX (  `COD_PLANO` );

ALTER TABLE  `detalhes_plano` ADD FOREIGN KEY (  `COD_PLANO` ) REFERENCES  `aggenda`.`plano` (
`CODIGO`
) ON DELETE CASCADE ON UPDATE RESTRICT ;

INSERT INTO  `aggenda`.`plano` (
`CODIGO` ,
`NOME` ,
`VALOR_MENSAL` ,
`VALOR_ANUAL` ,
`DESCRICAO`
)
VALUES (
NULL ,  'Plano free',  '0',  '0',  'Grátis'
);

INSERT INTO  `aggenda`.`detalhes_plano` (
`CODIGO` ,
`COD_PLANO` ,
`NUM_AGENDAMENTOS` ,
`NUM_SERVICOS` ,
`LEMBRETE_EMAIL` ,
`NUM_TEMPLATES` ,
`PERSONALIZA_TEMPLATE` ,
`NUM_FOTOS_LOCAL` ,
`PRAZO_AGENDAMENTO` ,
`NUM_FUNCIONARIO_LOCAL`
)
VALUES (
NULL ,  '1',  '50',  '2',  '0', NULL ,  '0',  '2',  '2',  '2'
);

CREATE TABLE `agendamento` (
 `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
 `COD_CLIENTE` int(11) NOT NULL,
 `START` datetime NOT NULL,
 `END` datetime NOT NULL,
 `COD_FUNCIONARIO_SALA` int(11) NOT NULL,
 `CONFIRMADO` tinyint(1) NOT NULL,
 `DATA_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`CODIGO`),
 KEY `COD_CLIENTE` (`COD_CLIENTE`,`COD_FUNCIONARIO_SALA`),
 KEY `COD_FUNCIONARIO_SALA` (`COD_FUNCIONARIO_SALA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE  `agendamento` ADD INDEX (  `COD_FUNCIONARIO_SALA` );

ALTER TABLE  `agendamento` ADD FOREIGN KEY (  `COD_FUNCIONARIO_SALA` ) REFERENCES  `aggenda`.`funcionario` (
`CODIGO`
) ON DELETE RESTRICT ON UPDATE RESTRICT ;
